SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE
	posts_comments_files,
    posts_comments,
    posts_files,
    posts,
	tickets_comments_files,
    tickets_comments,
    tickets_files,
    tickets_labels,
	labels,
    users_communities_roles,
    communities_roles,
	users_global_roles,
    global_roles,
    tickets_assignment_history,
	tickets_assignees,
    tickets_states_history,
    tickets,
    ticket_states,
	users_communities,
    communities,
    community_types,
    comments,
    avatars,
	moderations,
    authorships,
    users,
    moderation_states,
    timestamps,
    addresses,
	files;

SET FOREIGN_KEY_CHECKS = 0;
