// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Address struct {
	ID         []byte
	Street     sql.NullString
	Locality   sql.NullString
	City       sql.NullString
	Province   sql.NullString
	PostalCode sql.NullString
	Country    sql.NullString
	Latitude   sql.NullFloat64
	Longitude  sql.NullFloat64
}

type Authorship struct {
	ID         []byte
	CreatorID  sql.NullString
	ModifierID sql.NullString
}

type Avatar struct {
	UserID      []byte
	TimestampID []byte
	FileID      sql.NullString
	Width       sql.NullInt32
	Height      sql.NullInt32
}

type Comment struct {
	ID           []byte
	ModerationID []byte
	TimestampID  []byte
	AddressID    []byte
	CreatorID    sql.NullString
	Content      string
	Pinned       bool
}

type CommunitiesRole struct {
	ID           []byte
	CommunityID  []byte
	TimestampID  []byte
	AuthorshipID []byte
	Name         string
	Permissions  uint64
	Description  sql.NullString
}

type Community struct {
	ID           []byte
	TypeID       []byte
	RootID       []byte
	ModerationID []byte
	TimestampID  []byte
	AddressID    []byte
	CreatorID    sql.NullString
	Name         string
	Description  sql.NullString
}

type CommunityType struct {
	ID          []byte
	Name        string
	Description string
}

type File struct {
	ID         []byte
	Checksum   []byte
	StorageKey string
	MimeType   string
	FileSize   uint64
}

type GlobalRole struct {
	ID          []byte
	Name        string
	Permissions uint64
	Description string
}

type Label struct {
	ID           []byte
	CommunityID  []byte
	TimestampID  []byte
	AuthorshipID []byte
	Name         string
	Color        string
	Description  sql.NullString
}

type Moderation struct {
	ID          []byte
	StateID     []byte
	TimestampID []byte
	ModeratorID sql.NullString
}

type ModerationState struct {
	ID          []byte
	Name        string
	Description string
}

type Post struct {
	ID           []byte
	CommunityID  []byte
	ModerationID []byte
	TimestampID  []byte
	AddressID    []byte
	CreatorID    sql.NullString
	Title        string
	Content      string
}

type PostsComment struct {
	ID        []byte
	PostID    []byte
	CommentID []byte
}

type PostsCommentsFile struct {
	PostsCommentID []byte
	FileID         []byte
	Name           string
	CreatedAt      time.Time
}

type PostsFile struct {
	PostID    []byte
	FileID    []byte
	Name      string
	CreatedAt time.Time
}

type Ticket struct {
	ID           []byte
	CommunityID  []byte
	ModerationID []byte
	TimestampID  []byte
	AddressID    []byte
	StateID      []byte
	CreatorID    sql.NullString
	Title        string
	Description  sql.NullString
}

type TicketState struct {
	ID   []byte
	Name string
}

type TicketsAssignee struct {
	TicketID []byte
	UserID   []byte
}

type TicketsAssignmentHistory struct {
	ID         []byte
	TicketID   []byte
	CreatorID  sql.NullString
	AssigneeID sql.NullString
	CreatedAt  time.Time
	Added      bool
}

type TicketsComment struct {
	ID        []byte
	TicketID  []byte
	CommentID []byte
}

type TicketsCommentsFile struct {
	TicketsCommentID []byte
	FileID           []byte
	Name             string
	CreatedAt        time.Time
}

type TicketsFile struct {
	TicketID  []byte
	FileID    []byte
	Name      string
	CreatedAt time.Time
}

type TicketsLabel struct {
	TicketID  []byte
	LabelID   []byte
	CreatedAt time.Time
}

type TicketsStatesHistory struct {
	ID        []byte
	StateID   []byte
	TicketID  []byte
	CreatorID sql.NullString
	CreatedAt time.Time
}

type Timestamp struct {
	ID        []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           []byte
	TimestampID  []byte
	AddressID    []byte
	Email        string
	FirstName    string
	LastName     string
	PasswordHash []byte
	MiddleName   sql.NullString
	ModerationID sql.NullString
}

type UsersCommunitiesRole struct {
	UserID    []byte
	RoleID    []byte
	CreatedAt time.Time
}

type UsersCommunity struct {
	UserID      []byte
	CommunityID []byte
	CreatedBy   time.Time
}

type UsersGlobalRole struct {
	UserID    []byte
	RoleID    []byte
	CreatedAt time.Time
}
