// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const getAddress = `-- name: GetAddress :one
SELECT id, street, locality, city, province, postal_code, country, latitude, longitude
FROM addresses
WHERE id = ?
`

func (q *Queries) GetAddress(ctx context.Context, id []byte) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddress, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.Locality,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
